baseURL: http://shirleywan-port.netlify.app/
languageCode: en-us
title: Portfolio Website for Shirley Wan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Shirley Wan. I'm a master student in LBS. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: swan.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0) 7925-711514
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    #quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
        #url: https://www.facebook.com
      #- icon: fa-instagram
       # label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Xueyu12
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.https://www.linkedin.com/in/shirley-wan-221812152/?originalSubdomain=cn
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
      - name: About
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: aboutme.jpg
        #subtitle: Ipsum Dolor Sit Amet
        title: About Me
        url: blogs/about_me
      - image: resume.jpg
        #subtitle: Feugiat Amet Tempus
        title: Resume
        url: blogs/resume
      - image: trip12.jpg
        subtitle: Traditonal Jiangnan Water Town
        title: Journey in Suzhou
        url: blogs/suzhou
      - image: trip2.jpg
        subtitle: Great Nature of the West East Part of China
        title: Journey in Lanzhou
        url: blogs/lanzhou
      - image: canada.jpg
        subtitle: London/ Toronto/ Montreal/ Quebec/ Vancouver 
        title: Exchange in Canada
        url: blogs/exchange
      - image: pic06.jpg
        #subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Oops
    enable: yes
    subtitle: "Wer mit Ungeheuern kämpft, mag zusehn, dass er nicht dabei zum Ungeheuer wird. Und wenn du lange in einen Abgrund blickst, blickt der Abgrund auch in dich hinein."
    title: Need not to know
url: blogs
